version: "3.9"

services:
  hmrs:
    container_name: hrms-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./hrms-app:/var/www/html
      - ./hrms-app/storage:/var/www/html/storage

  ai-service:
    container_name: ai-service-dev
    restart: unless-stopped
    ports:
      - "8100:8100"
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8100
      --reload
    environment:
      MODE: development

  celery-worker:
    build: ./ai-service
    container_name: celery-worker-dev
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ./ai-service/src:/app
    depends_on:
      - redis
    networks:
      - backend

  redis:
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"

  # postgres:
  #   container_name: postgres-dev
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
