[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:fastapi]
process_name=%(program_name)s_%(process_num)02d
command=uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level info
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/app/data/logs/fastapi.log
stopwaitsecs=3600


[program:celery-worker]
process_name=%(program_name)s_%(process_num)02d
command=celery -A app.celery_app worker --loglevel=info --concurrency=2 --max-tasks-per-child=1000 --prefetch-multiplier=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/app/data/logs/worker.log
stopwaitsecs=3600


[program:celery-beat]
process_name=%(program_name)s_%(process_num)02d
command=celery -A app.celery_app beat --loglevel=info
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/app/data/logs/beat.log
stopwaitsecs=3600


[program:flower-monitor]
process_name=%(program_name)s_%(process_num)02d
command=celery -A app.celery_app flower --port=5555
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/app/data/logs/flower.log
stopwaitsecs=3600